name: PBL4_smart_home
description: A new Flutter project.

environment:
  sdk: '^3.9.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  charts_flutter_new: ^0.12.0
  flutter_mjpeg: ^2.0.4 # Hoặc package hiển thị MJPEG stream khác
  webview_flutter: ^4.4.2
  web_socket_channel: ^3.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
